### ISSUE TITLE
List different revisions for each version of a library in the new ConanCenter

### ISSUE THREAD

**Issue by raz-zelig** [conan-io/web#67] opened 2023-08-01 09:40 UTC
Whenever I wanted to add a Conan library to my project, I always went to ConanCenter first, chose a version, and chose a revision with the settings that I use in order to not build the library, when building my project (ie. use a pre-built one from Conan).
Will it be possible in the new ConanCenter?

CC @prince-chrismc

**Comment by memsharded** [comment] 2023-08-01 10:02
This would be a duplicate of https://github.com/conan-io/web/issues/62, please track that ticket and check the comments there. Thanks.

**Closed by memsharded** 2023-08-01 10:02 UTC
Labels: duplicate
